version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  versioning-strategy: lockfile-only
  rebase-strategy: disabled
