inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - acumatica.gemspec
    - spec/**/*.rb

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/OpenStructUse:
  Enabled: false

Style/StringLiterals:
  Enabled: false
